SHOES = "SHOES"
CLOTHES = "CLOTHES"
OTHERS = "OTHERS"

CATEGORY = [
    (SHOES, SHOES),
    (CLOTHES, CLOTHES),
    (OTHERS, OTHERS),
]

CARD = "CARD"
CASH = "CASH"
NET_BANKING = "NET_BANKING"
PAYMENT_TYPE = [
    (CARD,CARD),
    (CASH,CASH),
    (NET_BANKING,NET_BANKING)
]