# Generated by Django 5.0.6 on 2024-06-20 05:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('843de774-e359-49bc-b379-ee5a411b2c64'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('4a45ec7f-327d-42c2-9c0e-9feec9ffd022'), editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=25)),
                ('categories', models.CharField(choices=[('SHOES', 'SHOES'), ('CLOTHES', 'CLOTHES'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=20)),
                ('sale_date', models.DateTimeField()),
                ('unit_price', models.FloatField(max_length=8)),
                ('discount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('00e98412-0c5a-470b-a79c-b96edaa687df'), editable=False, primary_key=True, serialize=False)),
                ('shipment_cost', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('NET_BANKING', 'NET_BANKING')], default='CASH', max_length=20)),
                ('quantity_sold', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-pk'],
            },
        ),
    ]
